-- 코드를 입력하세요
SELECT TO_CHAR(OI.SALES_DATE,'YYYY') YEAR, TO_NUMBER(TO_CHAR(OI.SALES_DATE,'MM')) MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) USERS
FROM USER_INFO UI, ONLINE_SALE OI
WHERE UI.USER_ID = OI.USER_ID AND
GENDER IS NOT NULL
GROUP BY TO_CHAR(OI.SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(OI.SALES_DATE,'MM')), GENDER
ORDER BY YEAR, MONTH, GENDER;
